<?php

namespace Database\Seeders;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class FootballSeeder extends Seeder
{
    public function run(): void
    {
        // 1. Daftar Liga (ID 1-8)
        DB::table('leagues')->insert([
            ['id' => 1, 'name' => 'Liga 1 Indonesia'],
            ['id' => 2, 'name' => 'Premier League'],
            ['id' => 3, 'name' => 'La Liga'],
            ['id' => 4, 'name' => 'Serie A'],
            ['id' => 5, 'name' => 'Bundesliga'],
            ['id' => 6, 'name' => 'Ligue 1'],
            ['id' => 7, 'name' => 'Liga 2 Indonesia'],
            ['id' => 8, 'name' => 'Champions League'],
        ]);

        // 2. Daftar Lengkap Klub (Sesuai data 2026)
        $teams = [
            // Liga 1 Indonesia (ID 1)
            ['league_id' => 1, 'name' => 'Arema FC'],
            ['league_id' => 1, 'name' => 'Bali United'],
            ['league_id' => 1, 'name' => 'Bhayangkara Presisi Lampung FC'],
            ['league_id' => 1, 'name' => 'Dewa United'],
            ['league_id' => 1, 'name' => 'Madura United'],
            ['league_id' => 1, 'name' => 'Malut United'],
            ['league_id' => 1, 'name' => 'Persib Bandung'],
            ['league_id' => 1, 'name' => 'Persija Jakarta'],
            ['league_id' => 1, 'name' => 'Persik Kediri'],
            ['league_id' => 1, 'name' => 'Persis Solo'],
            ['league_id' => 1, 'name' => 'Persebaya Surabaya'],
            ['league_id' => 1, 'name' => 'Persita Tangerang'],
            ['league_id' => 1, 'name' => 'PSBS Biak'],
            ['league_id' => 1, 'name' => 'PSIM Yogyakarta'],
            ['league_id' => 1, 'name' => 'PSM Makassar'],
            ['league_id' => 1, 'name' => 'Semen Padang'],
            ['league_id' => 1, 'name' => 'Borneo FC Samarinda'],
            ['league_id' => 1, 'name' => 'PSS Sleman'],

            // Premier League (ID 2)
            ['league_id' => 2, 'name' => 'Arsenal'],
            ['league_id' => 2, 'name' => 'Aston Villa'],
            ['league_id' => 2, 'name' => 'Bournemouth'],
            ['league_id' => 2, 'name' => 'Brentford'],
            ['league_id' => 2, 'name' => 'Brighton & Hove Albion'],
            ['league_id' => 2, 'name' => 'Burnley'],
            ['league_id' => 2, 'name' => 'Chelsea'],
            ['league_id' => 2, 'name' => 'Crystal Palace'],
            ['league_id' => 2, 'name' => 'Everton'],
            ['league_id' => 2, 'name' => 'Fulham'],
            ['league_id' => 2, 'name' => 'Leeds United'],
            ['league_id' => 2, 'name' => 'Liverpool'],
            ['league_id' => 2, 'name' => 'Manchester City'],
            ['league_id' => 2, 'name' => 'Manchester United'],
            ['league_id' => 2, 'name' => 'Newcastle United'],
            ['league_id' => 2, 'name' => 'Nottingham Forest'],
            ['league_id' => 2, 'name' => 'Sunderland'],
            ['league_id' => 2, 'name' => 'Tottenham Hotspur'],
            ['league_id' => 2, 'name' => 'West Ham United'],
            ['league_id' => 2, 'name' => 'Wolverhampton Wanderers'],

            // La Liga (ID 3)
            ['league_id' => 3, 'name' => 'Alavés'],
            ['league_id' => 3, 'name' => 'Athletic Club'],
            ['league_id' => 3, 'name' => 'Atlético Madrid'],
            ['league_id' => 3, 'name' => 'Barcelona'],
            ['league_id' => 3, 'name' => 'Celta Vigo'],
            ['league_id' => 3, 'name' => 'Elche'],
            ['league_id' => 3, 'name' => 'Espanyol'],
            ['league_id' => 3, 'name' => 'Getafe'],
            ['league_id' => 3, 'name' => 'Girona'],
            ['league_id' => 3, 'name' => 'Levante'],
            ['league_id' => 3, 'name' => 'Mallorca'],
            ['league_id' => 3, 'name' => 'Osasuna'],
            ['league_id' => 3, 'name' => 'Rayo Vallecano'],
            ['league_id' => 3, 'name' => 'Real Betis'],
            ['league_id' => 3, 'name' => 'Real Madrid'],
            ['league_id' => 3, 'name' => 'Real Oviedo'],
            ['league_id' => 3, 'name' => 'Real Sociedad'],
            ['league_id' => 3, 'name' => 'Sevilla'],
            ['league_id' => 3, 'name' => 'Valencia'],
            ['league_id' => 3, 'name' => 'Villarreal'],

            // Serie A (ID 4)
            ['league_id' => 4, 'name' => 'Atalanta'],
            ['league_id' => 4, 'name' => 'Bologna'],
            ['league_id' => 4, 'name' => 'Cagliari'],
            ['league_id' => 4, 'name' => 'Como'],
            ['league_id' => 4, 'name' => 'Cremonese'],
            ['league_id' => 4, 'name' => 'Fiorentina'],
            ['league_id' => 4, 'name' => 'Genoa'],
            ['league_id' => 4, 'name' => 'Hellas Verona'],
            ['league_id' => 4, 'name' => 'Inter Milan'],
            ['league_id' => 4, 'name' => 'Juventus'],
            ['league_id' => 4, 'name' => 'Lazio'],
            ['league_id' => 4, 'name' => 'Lecce'],
            ['league_id' => 4, 'name' => 'AC Milan'],
            ['league_id' => 4, 'name' => 'Napoli'],
            ['league_id' => 4, 'name' => 'Parma'],
            ['league_id' => 4, 'name' => 'Pisa'],
            ['league_id' => 4, 'name' => 'Roma'],
            ['league_id' => 4, 'name' => 'Sassuolo'],
            ['league_id' => 4, 'name' => 'Torino'],
            ['league_id' => 4, 'name' => 'Udinese'],

            // Bundesliga (ID 5)
            ['league_id' => 5, 'name' => 'Augsburg'],
            ['league_id' => 5, 'name' => 'Bayer Leverkusen'],
            ['league_id' => 5, 'name' => 'Bayern München'],
            ['league_id' => 5, 'name' => 'Borussia Dortmund'],
            ['league_id' => 5, 'name' => 'Borussia Mönchengladbach'],
            ['league_id' => 5, 'name' => 'Eintracht Frankfurt'],
            ['league_id' => 5, 'name' => 'FC Köln'],
            ['league_id' => 5, 'name' => 'Freiburg'],
            ['league_id' => 5, 'name' => 'Hamburger SV'],
            ['league_id' => 5, 'name' => 'Heidenheim'],
            ['league_id' => 5, 'name' => 'Hoffenheim'],
            ['league_id' => 5, 'name' => 'Mainz 05'],
            ['league_id' => 5, 'name' => 'RB Leipzig'],
            ['league_id' => 5, 'name' => 'St. Pauli'],
            ['league_id' => 5, 'name' => 'Union Berlin'],
            ['league_id' => 5, 'name' => 'VfB Stuttgart'],
            ['league_id' => 5, 'name' => 'VfL Wolfsburg'],
            ['league_id' => 5, 'name' => 'Werder Bremen'],

            // Ligue 1 (ID 6)
            ['league_id' => 6, 'name' => 'Angers'],
            ['league_id' => 6, 'name' => 'Auxerre'],
            ['league_id' => 6, 'name' => 'Brest'],
            ['league_id' => 6, 'name' => 'Le Havre'],
            ['league_id' => 6, 'name' => 'Lens'],
            ['league_id' => 6, 'name' => 'Lille'],
            ['league_id' => 6, 'name' => 'Lorient'],
            ['league_id' => 6, 'name' => 'Lyon'],
            ['league_id' => 6, 'name' => 'Marseille'],
            ['league_id' => 6, 'name' => 'Metz'],
            ['league_id' => 6, 'name' => 'Monaco'],
            ['league_id' => 6, 'name' => 'Nantes'],
            ['league_id' => 6, 'name' => 'Nice'],
            ['league_id' => 6, 'name' => 'Paris FC'],
            ['league_id' => 6, 'name' => 'Paris Saint-Germain'],
            ['league_id' => 6, 'name' => 'Rennes'],
            ['league_id' => 6, 'name' => 'Strasbourg'],
            ['league_id' => 6, 'name' => 'Toulouse'],

            // Liga 2 Indonesia (ID 7)
            ['league_id' => 7, 'name' => 'Persiraja Banda Aceh'],
            ['league_id' => 7, 'name' => 'PSPS Pekanbaru'],
            ['league_id' => 7, 'name' => 'PSMS Medan'],
            ['league_id' => 7, 'name' => 'Sriwijaya FC'],
            ['league_id' => 7, 'name' => 'PSKC Cimahi'],
            ['league_id' => 7, 'name' => 'Persikabo 1973'],
            ['league_id' => 7, 'name' => 'Dejan FC'],
            ['league_id' => 7, 'name' => 'Bekasi City'],
            ['league_id' => 7, 'name' => 'Persikota Tangerang'],
            ['league_id' => 7, 'name' => 'Adhyaksa FC'],
            ['league_id' => 7, 'name' => 'Persela Lamongan'],
            ['league_id' => 7, 'name' => 'Deltras FC'],
            ['league_id' => 7, 'name' => 'Persibo Bojonegoro'],
            ['league_id' => 7, 'name' => 'Gresik United'],
            ['league_id' => 7, 'name' => 'Persipal Palu'],
            ['league_id' => 7, 'name' => 'Persipura Jayapura'],
            ['league_id' => 7, 'name' => 'Persewar Waropen'],
            ['league_id' => 7, 'name' => 'Persekat Tegal'],
            ['league_id' => 7, 'name' => 'NZR Sumbersari'],
            ['league_id' => 7, 'name' => 'Sulut United'],

            // Champions League (ID 8)
            ['league_id' => 8, 'name' => 'Arsenal'],
            ['league_id' => 8, 'name' => 'Aston Villa'],
            ['league_id' => 8, 'name' => 'Chelsea'],
            ['league_id' => 8, 'name' => 'Liverpool'],
            ['league_id' => 8, 'name' => 'Manchester City'],
            ['league_id' => 8, 'name' => 'Newcastle United'],
            ['league_id' => 8, 'name' => 'Tottenham Hotspur'],
            ['league_id' => 8, 'name' => 'Barcelona'],
            ['league_id' => 8, 'name' => 'Real Madrid'],
            ['league_id' => 8, 'name' => 'Atlético Madrid'],
            ['league_id' => 8, 'name' => 'Athletic Club'],
            ['league_id' => 8, 'name' => 'Villarreal'],
            ['league_id' => 8, 'name' => 'Napoli'],
            ['league_id' => 8, 'name' => 'Inter Milan'],
            ['league_id' => 8, 'name' => 'Atalanta'],
            ['league_id' => 8, 'name' => 'Juventus'],
            ['league_id' => 8, 'name' => 'Bayern München'],
            ['league_id' => 8, 'name' => 'Bayer Leverkusen'],
            ['league_id' => 8, 'name' => 'Borussia Dortmund'],
            ['league_id' => 8, 'name' => 'Eintracht Frankfurt'],
            ['league_id' => 8, 'name' => 'Paris Saint-Germain'],
            ['league_id' => 8, 'name' => 'Marseille'],
            ['league_id' => 8, 'name' => 'Monaco'],
            ['league_id' => 8, 'name' => 'Nice'],
            ['league_id' => 8, 'name' => 'PSV Eindhoven'],
            ['league_id' => 8, 'name' => 'Ajax'],
            ['league_id' => 8, 'name' => 'Sporting CP'],
            ['league_id' => 8, 'name' => 'Union Saint-Gilloise'],
            ['league_id' => 8, 'name' => 'Galatasaray'],
            ['league_id' => 8, 'name' => 'Olympiacos'],
            ['league_id' => 8, 'name' => 'Slavia Praha'],
            ['league_id' => 8, 'name' => 'Red Bull Salzburg'],
            ['league_id' => 8, 'name' => 'Celtic'],
            ['league_id' => 8, 'name' => 'Basel'],
            ['league_id' => 8, 'name' => 'Bodø/Glimt'],
            ['league_id' => 8, 'name' => 'Club Brugge'],
            ['league_id' => 8, 'name' => 'Dinamo Zagreb'],
        ];

        DB::table('teams')->insert($teams);
    }
}